import RestaurantImages from './restaurantImagesElement.js'
let restaurants = [
    {restaurantName:"Joe's Gelato",restaurantImage:RestaurantImages["Joe's Gelato"].restaurantCoverImage,restaurantEta:'10-30',restaurantTagline:'Desert, Ice cream, £££',menu:[
      {menuSectionTitle:'Gelato',menuSectionContent:[{title:'Vanilla',image:RestaurantImages["Joe's Gelato"].menuItems['Vanilla'],description:'Creamy Italian frozen dessert made from milk, sugar, and vanilla flavor',price:8.5},{title:'Chocolate',image:RestaurantImages["Joe's Gelato"].menuItems['Chocolate'],description:'Luxurious, chocolate-flavored frozen dessert with a smooth and creamy texture',price:9.5},{title:'Mint',image:RestaurantImages["Joe's Gelato"].menuItems['Mint'],description:'Refreshing burst of cool, crisp flavor in a creamy and indulgent frozen treat',price:8.95}]},
      {menuSectionTitle:'Coffee',menuSectionContent:[{title:'Flat white',image:RestaurantImages["Joe's Gelato"].menuItems['Flat white'],description:'Velvety smooth espresso-based coffee with a rich and creamy microfoam, artfully crafted to bring out the complex flavors of the beans',price:4.5},{title:'Latte',image:RestaurantImages["Joe's Gelato"].menuItems['Latte'],description:'Smooth and creamy espresso-based coffee, topped with a generous dollop of frothy milk',price:4.5},{title:'Caffè Americano',image:RestaurantImages["Joe's Gelato"].menuItems['Caffè Americano'],description:'Strong and robust coffee, with a bold and full-bodied flavor',price:3.5}]},
    ]},
    {restaurantName:"Joe's Diner",restaurantImage:RestaurantImages["Joe's Diner"].restaurantCoverImage,restaurantEta:'50+',restaurantTagline:'American, burguers, ££',menu:[
      {menuSectionTitle:'Our specialties',menuSectionContent:[{title:'Cowboy classic',image:RestaurantImages["Joe's Diner"].menuItems['Cowboy classic'],description:'Symphony of flavors, with a juicy and succulent patty grilled to perfection and topped with a medley of artisanal description',price:10.5},{title:'Ultimate stack',image:RestaurantImages["Joe's Diner"].menuItems['Ultimate stack'],description:'A masterpiece of culinary creativity, with a juicy and succulent patty made from the finest meat, grilled to perfection and nestled in a soft bun',price:10.5}]},
      {menuSectionTitle:'Classic burgers',menuSectionContent:[{title:'Double cheese',image:RestaurantImages["Joe's Diner"].menuItems['Double cheese'],description:'Two beef patties and two slices of cheese that will blow your mind',price:7.5},{title:'Triple bacon',image:RestaurantImages["Joe's Diner"].menuItems['Triple bacon'],description:'Indulge in the ultimate bacon experience with our triple bacon burger, featuring three types of bacon',price:10.5}]},
      {menuSectionTitle:'Ribs',menuSectionContent:[{title:'BBQ ribs',image:RestaurantImages["Joe's Diner"].menuItems['BBQ ribs'],description:'slow-cooked and coated in a sweet and tangy barbecue sauce',price:19.95},{title:'Ribeye steak',image:RestaurantImages["Joe's Diner"].menuItems['Ribeye steak'],description:'Cut of beef that includes a rib bone and is known for its rich, beefy flavor',price:13.5},{title:'Rib roast',image:RestaurantImages["Joe's Diner"].menuItems['Rib roast'],description:'A cut of meat that includes the rib bones and is often roasted in the oven or on a grill',price:22.5}]},
    ]},
    {restaurantName:"Spices of the Andes",restaurantImage:RestaurantImages["Spices of the Andes"].restaurantCoverImage,restaurantEta:'5-15',restaurantTagline:'Peruvian, Latin, Vegetarian friendly, ££',menu:[
      {menuSectionTitle:'Our specialties',menuSectionContent:[{title:'Ceviche',image:RestaurantImages["Spices of the Andes"].menuItems['Ceviche'],description:'A dish made of fresh raw fish or seafood marinated in citrus juice and spiced with chili peppers and ají, a type of Peruvian pepper',price:12.95},{title:'Lomo saltado',image:RestaurantImages["Spices of the Andes"].menuItems['Lomo saltado'],description:'A stir-fry dish made with marinated slices of beef, tomatoes, onions, and French fries, served with white rice',price:11.5},{title:'Pollo a la brasa',image:RestaurantImages["Spices of the Andes"].menuItems['Pollo a la brasa'],description:'A rotisserie chicken dish that is marinated in a mixture of spices and herbs and cooked over an open fire or grill',price:11.95}]},
      {menuSectionTitle:'Appetizers',menuSectionContent:[{title:'Causa rellena',image:RestaurantImages["Spices of the Andes"].menuItems['Causa rellena'],description:'Made of mashed potatoes that is filled with chicken, tuna, or vegetables topped with avocado or hard-boiled egg',price:6.95},{title:'Anticuchos',image:RestaurantImages["Spices of the Andes"].menuItems['Anticuchos'],description:'Grilled skewers of beef heart marinated in a mixture of spices and served with a side of potatoes',price:16.95},{title:'Empanadas',image:RestaurantImages["Spices of the Andes"].menuItems['Empanadas'],description:'Fried or baked pastries filled with a variety of fillings such as meat, cheese, or vegetables',price:5.95}]},
      {menuSectionTitle:'Chicken',menuSectionContent:[{title:'Pollo a la brasa',image:RestaurantImages["Spices of the Andes"].menuItems['Pollo a la brasa'],description:'A rotisserie chicken dish that is marinated in a mixture of spices and herbs and cooked over an open fire or grill',price:10.5},{title:'Arroz con pollo',image:RestaurantImages["Spices of the Andes"].menuItems['Arroz con pollo'],description:'A dish of rice cooked with chicken, vegetables, and spices, often served with a side of avocado or plantains',price:10.5},{title:'Pollo a la olla',image:RestaurantImages["Spices of the Andes"].menuItems['Pollo a la olla'],description:'A chicken stew made with potatoes, carrots, peas, and spices and served with white rice',price:8.95}]},
      {menuSectionTitle:'Fish & Seafood',menuSectionContent:[{title:'Jalea',image:RestaurantImages["Spices of the Andes"].menuItems['Jalea'],description:'A dish made of deep-fried fish or seafood, served with a side of onions, peppers, and a lime-based sauce',price:10.5},{title:'Camarones',image:RestaurantImages["Spices of the Andes"].menuItems['Camarones'],description:'A hearty shrimp chowder made with milk, potatoes, and spices, often served with a side of white rice',price:10.5},{title:'Escabeche',image:RestaurantImages["Spices of the Andes"].menuItems['Escabeche'],description:'A dish of marinated and cooked fish, served with a side of vegetables such as onions, peppers, and carrots',price:10.5}]},
    ]},
    {restaurantName:"Samurai Sushi",restaurantImage:RestaurantImages["Samurai Sushi"].restaurantCoverImage,restaurantEta:'5-15',restaurantTagline:'Sushi, Japanese specialty, ££££',menu:[
      {menuSectionTitle:'Sushi',menuSectionContent:[{title:'California roll',image:RestaurantImages["Samurai Sushi"].menuItems['California roll'],description:'A type of sushi roll filled with avocado, crab meat, and cucumber, often served with a side of soy sauce and wasabi',price:10.5},{title:'Spicy tuna roll',image:RestaurantImages["Samurai Sushi"].menuItems['Spicy tuna roll'],description:'A type of sushi roll filled with diced raw tuna mixed with a spicy mayonnaise sauce',price:10.5},{title:'Rainbow roll',image:RestaurantImages["Samurai Sushi"].menuItems['Rainbow roll'],description:'A type of sushi roll filled with a variety of raw fish, arranged in a colorful pattern on top of the roll',price:10.5}]},
      {menuSectionTitle:'Appetizers',menuSectionContent:[{title:'Edamame',image:RestaurantImages["Samurai Sushi"].menuItems['Edamame'],description:'Boiled and salted soybeans served in the pod, often served as a snack or appetizer',price:10.5},{title:'Takoyaki',image:RestaurantImages["Samurai Sushi"].menuItems['Takoyaki'],description:'Small ball-shaped snacks filled with diced octopus, tempura bits, and green onion',price:10.5},{title:'Gyoza',image:RestaurantImages["Samurai Sushi"].menuItems['Gyoza'],description:'Fried or steamed dumplings filled with a variety of ingredients such as meat, vegetables, or seafood',price:10.5}]},
      {menuSectionTitle:'Salads',menuSectionContent:[{title:'Sunomono',image:RestaurantImages["Samurai Sushi"].menuItems['Sunomono'],description:'A type of salad made with thinly sliced raw fish or vegetables that are marinated in vinegar and served with a side of rice',price:10.5},{title:'Wakame',image:RestaurantImages["Samurai Sushi"].menuItems['Wakame'],description:'A salad made with wakame, a type of edible seaweed, and mixed with ingredients such as sliced cucumber and sesame seeds',price:10.5}]},
    ]},
    {restaurantName:"Sapori D'Italia",restaurantImage:RestaurantImages["Sapori D'Italia"].restaurantCoverImage,restaurantEta:'10-30',restaurantTagline:'Italian, mediterranean cuisine, £££',menu:[
      {menuSectionTitle:'We recommend',menuSectionContent:[{title:'Spaghetti carbonara',image:RestaurantImages["Sapori D'Italia"].menuItems['Spaghetti carbonara'],description:'A pasta dish made with spaghetti, eggs, bacon, and parmesan cheese',price:10.5},{title:'Margherita pizza',image:RestaurantImages["Sapori D'Italia"].menuItems['Margherita pizza'],description:'A pizza topped with tomato sauce, mozzarella cheese, and fresh basil',price:10.5},{title:'Risotto alla Milanese',image:RestaurantImages["Sapori D'Italia"].menuItems['Risotto alla Milanese'],description:'A creamy rice dish made with saffron and parmesan cheese, often served with a variety of meats or vegetables',price:10.5}]},
      {menuSectionTitle:'Pasta',menuSectionContent:[{title:'Bolognese sauce',image:RestaurantImages["Sapori D'Italia"].menuItems['Bolognese sauce'],description:'A meat-based sauce made with ground beef, tomatoes, and vegetables, served over pasta',price:10.5},{title:'Fettuccine Alfredo',image:RestaurantImages["Sapori D'Italia"].menuItems['Fettuccine Alfredo'],description:'A pasta dish made with fettuccine noodles and a creamy cheese sauce',price:10.5}]},
      {menuSectionTitle:'Pizza',menuSectionContent:[{title:'Margherita',image:RestaurantImages["Sapori D'Italia"].menuItems['Margherita'],description:'A pizza topped with tomato sauce, mozzarella cheese, and fresh basil',price:10.5},{title:'Pepperoni',image:RestaurantImages["Sapori D'Italia"].menuItems['Pepperoni'],description:'A pizza topped with tomato sauce, mozzarella cheese, and spicy pepperoni slices',price:10.5},{title:'Four cheese',image:RestaurantImages["Sapori D'Italia"].menuItems['Four cheese'],description:'A pizza topped with a blend of four different types of cheese, such as mozzarella, parmesan, gorgonzola, and fontina',price:10.5}]},
    ]},
    {restaurantName:"Juan in a Million",restaurantImage:RestaurantImages["Juan in a Million"].restaurantCoverImage,restaurantEta:'10-30',restaurantTagline:'Mexican, tex mex, ££',menu:[
      {menuSectionTitle:'Our favourites',menuSectionContent:[{title:'Tacos',image:RestaurantImages["Juan in a Million"].menuItems['Tacos'],description:'A small, hand-sized corn or wheat tortilla folded or rolled around a filling of meat, seafood, or vegetables',price:10.5},{title:'Burritos',image:RestaurantImages["Juan in a Million"].menuItems['Burritos'],description:'A flour tortilla wrapped or folded around a filling of meat, seafood, beans, and vegetables',price:10.5},{title:'Enchiladas',image:RestaurantImages["Juan in a Million"].menuItems['Enchiladas'],description:'A corn tortilla filled with meat, seafood, or vegetables and rolled or folded, then covered in a spicy sauce and cheese',price:10.5}]},
      {menuSectionTitle:'Texmex',menuSectionContent:[{title:'Fajitas',image:RestaurantImages["Juan in a Million"].menuItems['Fajitas'],description:'A dish made of grilled and sliced meat, served with a side of peppers and onions and wrapped in a flour tortilla',price:10.5},{title:'Nachos',image:RestaurantImages["Juan in a Million"].menuItems['Nachos'],description:'A dish made of tortilla chips topped with cheese, ground beef, beans, and toppings such as salsa, sour cream, and guacamole',price:10.5},{title:'Chimichangas',image:RestaurantImages["Juan in a Million"].menuItems['Chimichangas'],description:'A dish made of a burrito that is deep-fried and filled with a variety of ingredients such as meat, beans, and cheese',price:10.5}]},
      {menuSectionTitle:"Desserts",menuSectionContent:[{title:'Flan',image:RestaurantImages["Juan in a Million"].menuItems['Flan'],description:'A creamy, caramel-topped custard made with eggs and milk',price:10.5},{title:'Sopapillas',image:RestaurantImages["Juan in a Million"].menuItems['Sopapillas'],description:'A fried pastry dusted with powdered sugar and served with a side of honey or chocolate sauce',price:10.5},{title:'Churros',image:RestaurantImages["Juan in a Million"].menuItems['Churros'],description:'A deep-fried doughnut-like pastry dusted with powdered sugar and served with a side of chocolate sauce',price:10.5}]}
    ]},
  ]
export default restaurants